# The stanford_travisci_scripts repository contains external scripts
# used here to configure server and build a self-service site.
# https://github.com/SU-SWS/stanford_travisci_scripts

language: php
php:
  - '7.1'

sudo: required

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # download external repository with Stanford Travis CI scripts
  - if [ ! -z $SCRIPTS_BRANCH ]; then SCRIPTS_BRANCH="-b $SCRIPTS_BRANCH"; fi
  - git clone $SCRIPTS_BRANCH https://github.com/SU-SWS/stanford_travisci_scripts.git $HOME/stanford_travisci_scripts
  - chmod +x $HOME/stanford_travisci_scripts/bin/*.sh

install:
  # install j8 site, start webserver and selenium webdriver
  - $HOME/stanford_travisci_scripts/bin/install.sh
