# The stanford_travisci_scripts repository contains external scripts
# used here to configure server and build a self-service site.
# https://github.com/SU-SWS/stanford_travisci_scripts

env:
  - REPOSITORY_NAME="stanford_bean_types"
  - PRODUCT_NAME="stanford"
  - ENABLE_MODULES=""
  - DISABLE_MODULES="webauth"
  - DEPLOYER_BRANCH=""
  - DRUPAL_PROFILE_BRANCH=""
  - CLICKY_BRANCH=""
  - SCRIPTS_BRANCH=""

language: php
php:
  - '5.6'

sudo: required

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache
    - $HOME/.drush/cache
    - $HOME/stanford_travisci_scripts
    - $HOME/Stanford-Drupal-Profile
    - $HOME/stanford-jumpstart-deployer

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # download external repository with Stanford Travis CI scripts
  - if [ -z "$(ls -A $HOME/stanford_travisci_scripts)" ]; then git clone https://github.com/SU-SWS/stanford_travisci_scripts.git $HOME/stanford_travisci_scripts; fi
  - git -C $HOME/stanford_travisci_scripts checkout $SCRIPTS_BRANCH; git -C $HOME/stanford_travisci_scripts pull
  - chmod +x $HOME/stanford_travisci_scripts/bin/*.sh
  # install composer packages
  - $HOME/stanford_travisci_scripts/bin/before_install.sh

install:
  # install self-service site, disable webauth module, start webserver and selenium webdriver
  - $HOME/stanford_travisci_scripts/bin/install.sh

before_script:
  # download linky_clicky, grab related tests, and start xvfb virtual display
  - $HOME/stanford_travisci_scripts/bin/before_script.sh

script:
  # make sure shell can find drush and run behat tests here, so Travis CI reports accurate results
  - $HOME/stanford_travisci_scripts/bin/script.sh
