# The stanford_travisci_scripts repository contains external scripts
# used here to configure server and build a self-service site.
# https://github.com/SU-SWS/stanford_travisci_scripts

# REPOSITORY_NAME:
# Enter the name of this repository, ie. stanford_bean_types
#
# PRODUCT_NAME:
# Leave blank to install a self-service site
# Or enter the product you would like to build.
# Options include
# - jumpstart
# - jumpstart-plus
# - jumpstart-lab
# - jumpstart-academic
# - jumpstart-engineering
#
# ENABLE_MODUES:
# Enter as a space separated string, modules that you would like to enable after
# the installation profile has run. Useful for adding additional items.
# Example: 
# stanford_gallery nobots
#
# DISABLE_MODULES:
# Enter as a space separated string, modules you would like disabled after the
# installation profile has run.
# Example:
# webauth webauth_extras
#
# DEPLOYER_BRANCH:
# Leave blank to use the default stanford-jumpstart-deployer branch.
# Example:
# basic-1234
#
# DRUPAL_PROFILE_BRANCH:
# Leave blank to use the default Stanford-Drupal-Profile branch.
#
# CLICKY_BRANCH:
# Leave blank to use the default linky_clicky branch. 
# Example:
# 4.x
#
# SCRIPTS_BRANCH:
# Leave blank to use the default stanford_travisci_scripts branch.
# Example:
# testing

env:
  global:
    - REPOSITORY_NAME=""
    - PRODUCT_NAME=""
    - ENABLE_MODULES=""
    - DISABLE_MODULES="webauth"
    - DEPLOYER_BRANCH=""
    - DRUPAL_PROFILE_BRANCH=""
    - CLICKY_BRANCH=""
    - SCRIPTS_BRANCH=""

language: php
php:
  - '5.6'

sudo: required

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # download external repository with Stanford Travis CI scripts
  - if [ ! -z $SCRIPTS_BRANCH ]; then SCRIPTS_BRANCH="-b $SCRIPTS_BRANCH"; fi
  - git clone $SCRIPTS_BRANCH https://github.com/SU-SWS/stanford_travisci_scripts.git $HOME/stanford_travisci_scripts
  - chmod +x $HOME/stanford_travisci_scripts/bin/*.sh
  # install composer packages
  - $HOME/stanford_travisci_scripts/bin/before_install.sh

install:
  # install self-service site, disable webauth module, start webserver and selenium webdriver
  - $HOME/stanford_travisci_scripts/bin/install.sh

before_script:
  # download linky_clicky, grab related tests, and start xvfb virtual display
  - $HOME/stanford_travisci_scripts/bin/before_script.sh

script:
  # make sure shell can find drush and run behat tests here, so Travis CI reports accurate results
  - $HOME/stanford_travisci_scripts/bin/script.sh
